### ISSUE TITLE
Add --net=host option for starting the docker container

### ISSUE THREAD

**Issue by chutium** [zalando-stups/taupage#48] opened 2015-06-03 15:03 UTC
we need such a feature for docker command for our Zookeeper appliance

for example we want to do this by senza create:

sudo docker run -p 2181:2181 -p 2888:2888 -p 3888:3888 -d --net=host efd7a9692031

we need to add this --net=host

Thanks

**Comment by hjacobs** [comment] 2015-06-03 18:35
@chutium IMHO I think your point is not valid --- Zookeeper uses TCP and the ZK instances can connect to each other with TCP without problems, check with the Cassandra guys how they do it (similar cluster problem: Cassandra nodes need to talk with each other)

**Comment by chutium** [comment] 2015-06-03 19:34
we tried to create distributed zk cluster with this docker option without STUPS toolbox, works fine.

each zk node try to connect themselves according to the address defined in zoo.cfg, without --net=host, the zoo.cfg in docker container must be set as (for example for server node 1):

server.1=localhost:2888:3888
server.2=private_ip2:2888:3888
...
...

but actually set a server location to localhost is wrong.

if we set the setting of server1 in docker container to something like:
server.1=private_ip1:2888:3888
server.2=private_ip2:2888:3888

then the docker container is not able to connect to itself using private IP of host, because docker container uses a virtual interface on host. (https://docs.docker.com/articles/networking/)

so the option --net=host solve this problem.

**Comment by sarnowski** [comment] 2015-06-03 19:40
You obviously have to use the Server IP/host and not dockers internal IP.

**Comment by chutium** [comment] 2015-06-03 19:41
yes, i mean server IP (ec2 instance's private IP)

**Comment by chutium** [comment] 2015-06-03 20:00
problem i want to point out is that, docker container can not connect to

**Comment by chutium** [comment] 2015-06-03 20:01
i have an idea, maybe we should check the security group... i will give a feedback tomorrow.

**Comment by drummerwolli** [comment] 2015-06-04 08:16
we tried it again, the problem is nothing with the network config, nor something else. ZK wants to bind a listening address, but since the docker container is listening behind the docker0 address, ZK canÄt bind this address. therefore we need to access the host system's network interface and bind the address and port directly there. see these logs here:

```2015-06-04 08:11:16,535 [myid:6] - ERROR [/172.31.7.6:3888:QuorumCnxManager$Listener@517] - Exception while listening
java.net.BindException: Cannot assign requested address```

172.31.7.6 is our internal IP form the host machine.

**Comment by chutium** [comment] 2015-06-04 09:36
so @femueller , please reassign or? setting of security group is not the problem.

**Comment by chutium** [comment] 2015-06-04 09:55
it seems we need to add something like
```
    if config.get('networktype'):
        yield '--net={}'.format(config.get('networktype'))
```
in ```get_other_options```, https://github.com/zalando-stups/taupage/blob/master/runtime/opt/zalando/runtime/Docker#L63

and somehow add this config in senza yaml or some other magical place...

**Comment by femueller** [comment] 2015-06-04 15:26
@chutium Please provide us a pull request with your feature request and update the [documentation](http://docs.stups.io/en/latest/components/taupage.html), which mentions that the networking flag is optional.

**Comment by femueller** [comment] 2015-06-04 15:55
Fixed by https://github.com/zalando-stups/taupage/pull/56

**Comment by femueller** [comment] 2015-06-04 15:56
Since the documentation is missing i'll keep it opened.

**Comment by chutium** [comment] 2015-06-04 17:35
ah, the PR for doc is here: https://github.com/zalando-stups/documentation/pull/20

i do not know how to reference PR across projects...

**Closed** 2015-06-05 08:22 UTC
Labels: enhancement
