### ISSUE TITLE
Screen session in taupage is dead after re-requesting access with piu

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/taupage#166] opened 2015-12-21 14:44 UTC
When connection to the instance is terminated due to access token expiry, you can find only a "dead" screen after re-connecting:
```

$ piu xxx.xxx.xxx.xxx "my reason"

**Comment by apfeiffer85** [comment] 2015-12-21 15:25
@a1exsh why do you run a screen session for more than  2 Days .... ?! 

There are some possible reason why or screen session is Dead ( connection timed out in the screen etc. ), depends on what do you do in the Screen Session. 

To go further, what's your use case ? 
What do you do in the Screen Session ?

**Comment by a1exsh** [comment] 2015-12-21 15:30
@apfeiffer85 I wasn't running it for 2 days, just for the usual 1 hour duration that the piu access token lasts.  Not sure why `screen -ls` shows the date as 18th, will try again.

The use case is pretty simple: don't lose the session because of access token expiry.  Did I already mention that it also makes shell and psql to lose their command history?  Pretty frustrating in my opinion.

**Comment by a1exsh** [comment] 2015-12-21 16:30
@apfeiffer85 the date reported by `screen ls` for the dead screen is incorrect, I don't know where does it get it from actually.  But the problem is that the screen session is killed after token expiry.  I've just tried it again and here's the console log:

```
Last login: Mon Dec 21 16:07:05 2015 from ip-172-31-0-189.eu-west-1.compute.internal
Your SSH access was granted by even (SSH access granting service) on 2015-12-21 15:26:18
oshulgin@ip-172-31-137-76:~$ screen -ls
There is a screen on:
	17237.pts-3.ip-172-31-137-76	(12/21/15 15:30:47)	(Attached)
1 Socket in /var/run/screen/S-oshulgin.

oshulgin@ip-172-31-137-76:~$ date
Mon Dec 21 16:24:24 UTC 2015
oshulgin@ip-172-31-137-76:~$ logout
Connection to 172.31.137.76 closed.
Connection to odd-eu-west-1.hackweek.zalan.do closed.
oshulgin@oshulgin01:~/src/open-street-map-server/web-map-service$ ssh -tA oshulgin@odd-eu-west-1.hackweek.zalan.do ssh -o StrictHostKeyChecking=no oshulgin@172.31.137.76
Your SSH access was revoked by even (SSH access granting service) on 2015-12-21 16:26:40
Connection to 172.31.137.76 closed.
Connection to odd-eu-west-1.hackweek.zalan.do closed.
oshulgin@oshulgin01:~/src/open-street-map-server/web-map-service$ piu 172.31.137.76 'monitor postgis'Requesting access to host 172.31.137.76 via odd-eu-west-1.hackweek.zalan.do for oshulgin..
Access to host odd-eu-west-1.hackweek.zalan.do/52.31.199.172 for user oshulgin was granted.
You can now access your server with the following command:
ssh -tA oshulgin@odd-eu-west-1.hackweek.zalan.do ssh -o StrictHostKeyChecking=no oshulgin@172.31.137.76
oshulgin@oshulgin01:~/src/open-street-map-server/web-map-service$ ssh -tA oshulgin@odd-eu-west-1.hackweek.zalan.do ssh -o StrictHostKeyChecking=no oshulgin@172.31.137.76
         _____                                   
Welcome /__   \__ _ _   _ _ __   __ _  __ _  ___ 
     to   / /\/ _` | | | | '_ \ / _` |/ _` |/ _ \
  STUPS  / / | (_| | |_| | |_) | (_| | (_| |  __/
         \/   \__,_|\__,_| .__/ \__,_|\__, |\___|
                         |_|          |___/      
        All actions will be logged!
Last login: Mon Dec 21 16:26:45 2015 from ip-172-31-0-189.eu-west-1.compute.internal
Your SSH access was granted by even (SSH access granting service) on 2015-12-21 16:26:56
oshulgin@ip-172-31-137-76:~$ screen -ls
There is a screen on:
	17237.pts-3.ip-172-31-137-76	(12/18/15 14:34:31)	(Dead ???)
Remove dead screens with 'screen -wipe'.
1 Socket in /var/run/screen/S-oshulgin.

oshulgin@ip-172-31-137-76:~$ screen -x
There is a screen on:
	17237.pts-3.ip-172-31-137-76	(12/18/15 14:34:31)	(Dead ???)
Remove dead screens with 'screen -wipe'.
There is no screen to be attached.
oshulgin@ip-172-31-137-76:~$ 
```

As you can see, there was a screen session started at 15:30 UTC with pid `17237`.  I've checked that the session is still there and I can attach to it around 16:24.  After the ssh session was terminated forcibly by the odd server, I can no longer resume my screen session.

**Comment by apfeiffer85** [comment] 2015-12-21 16:47
ok, gotcha, i guess thats reasonable .... but basically we now have tow different issues. 
The first one is the Screen issue, we have to investigate why this is happened .... will try to reproduce this. 

The second one is the loss of the Bash_history, can you please create another issue for that. 
And describe when this is happened. ( This should not happened .... that's definitely a bug ).

**Comment by hjacobs** [comment] 2015-12-21 16:54
FYI: We remove the user (and kill processes) on purpose --- we do not want long lasting sessions on EC2 instances...

**Comment by a1exsh** [comment] 2015-12-21 16:59
@hjacobs define long :-)  Seriously, is it too much to wish for?  I have a lengthy process to run there and I don't want to lose command history, nor lose the processes due to hangup.  The processes are actually there, but there's no way to reattach to them and continue (unless it was docker's main process).  The default 1 hour timeout makes it very frustrating to work with EC2 for my use case.

**Comment by hjacobs** [comment] 2015-12-21 17:07
@a1exsh you can specify a different timeout with Piu's `-t` option:

```
piu 172.31.1.1 'foo bar my reason' -t 1440 # one day (60*24)

**Comment by a1exsh** [comment] 2015-12-21 17:09
Oh, really? :-D  Thanks for that!

What stops everyone from doing that if you really don't want long sessions?  Is there a reaper script or something like that?

**Comment by hjacobs** [comment] 2015-12-21 17:12
We don't want you to prevent from working, but you might get questions like "why do you need an open session for a year" and "why do all your reasons say 'foobar'".. :smirk:

**Comment by a1exsh** [comment] 2015-12-21 17:13
Understood ;-)

**Comment by hjacobs** [comment] 2015-12-21 17:14
@a1exsh in Zalando context I can point you always to https://twitter.com/try_except_/status/675038395345825792 :smile:

**Comment by femueller** [comment] 2016-01-05 15:49
I'm closing this, since it's been clarified.

**Closed by femueller** 2016-01-05 15:49 UTC
