### ISSUE TITLE
Taupage loses shell history when session is killed on timeout

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/taupage#167] opened 2015-12-21 18:05 UTC
```
Last login: Mon Dec 21 16:48:20 2015 from ip-172-31-0-189.eu-west-1.compute.internal
Your SSH access was granted by even (SSH access granting service) on 2015-12-21 16:26:56
oshulgin@ip-172-31-137-76:~$ echo this will stay in history
this will stay in history
oshulgin@ip-172-31-137-76:~$ logout
Connection to 172.31.137.76 closed.

oshulgin@oshulgin01:~/src/open-street-map-server/web-map-service$ ssh -tA oshulgin@odd- ssh -o StrictHostKeyChecking=no oshulgin@172.31.137.76
Last login: Mon Dec 21 16:48:37 2015 from ip-172-31-0-189.eu-west-1.compute.internal
Your SSH access was granted by even (SSH access granting service) on 2015-12-21 16:26:56
oshulgin@ip-172-31-137-76:~$ history | tail -n2
   20  echo this will stay in history
   21  history | tail -n2
oshulgin@ip-172-31-137-76:~$ echo this will not stay though :-(
-bash: syntax error near unexpected token `('
oshulgin@ip-172-31-137-76:~$ history | tail -n2
   22  echo this will not stay though :-(
   23  history | tail -n2
oshulgin@ip-172-31-137-76:~$ Connection to 172.31.137.76 closed by remote host.
Connection to 172.31.137.76 closed.
Connection to odd closed.

oshulgin@oshulgin01:~/src/open-street-map-server/web-map-service$ piu 172.31.137.76 'test osm-import3'
Requesting access to host 172.31.137.76 via odd for oshulgin..
Access to host odd- for user oshulgin was granted.
You can now access your server with the following command:
ssh -tA oshulgin@odd- ssh -o StrictHostKeyChecking=no oshulgin@172.31.137.76
oshulgin@oshulgin01:~/src/open-street-map-server/web-map-service$ ssh -tA oshulgin@odd ssh -o StrictHostKeyChecking=no oshulgin@172.31.137.76
         _____                                   
Welcome /__   \__ _ _   _ _ __   __ _  __ _  ___ 
     to   / /\/ _` | | | | '_ \ / _` |/ _` |/ _ \
  STUPS  / / | (_| | |_| | |_) | (_| | (_| |  __/
         \/   \__,_|\__,_| .__/ \__,_|\__, |\___|
                         |_|          |___/      
        All actions will be logged!
Last login: Mon Dec 21 16:48:51 2015 from ip-172-31-0-189.eu-west-1.compute.internal
Your SSH access was granted by even (SSH access granting service) on 2015-12-21 18:01:46
oshulgin@ip-172-31-137-76:~$ history | tail -n2
   20  echo this will stay in history
   21  history | tail -n2
oshulgin@ip-172-31-137-76:~$ 
```

**Comment by femueller** [comment] 2016-01-06 12:39
I can not reproduce this. Also it seems more like a piu issue.

I've tried to reproduce it with a single instance and even after getting access revoked the history was still there after requesting access.

**Comment by a1exsh** [comment] 2016-01-06 14:50
Hey,

I can still reproduce it quite easily (stripped taupage banner an non-relevant output for readability).

1) Request access with short-lived session (`piu request-access -t 5 ...`), login and execute some command:
```sh
oshulgin@ip-172-31-171-204:~$ echo this should stay
this should stay
```

2) Logout normally (Ctrl+D):
```sh
oshulgin@ip-172-31-171-204:~$ logout
Connection to 172.31.171.204 closed.
Connection to odd-eu-west-1.acid.zalan.do closed.
```

3) Login again to verify history:
```sh
oshulgin@oshulgin01:~$ ssh -tA oshulgin@odd-eu-west-1.acid.zalan.do ssh -o StrictHostKeyChecking=no oshulgin@172.31.171.204
Last login: Wed Jan  6 14:37:15 2016 from ip-172-31-10-173.eu-west-1.compute.internal
Your SSH access was granted by even (SSH access granting service) on 2016-01-06 14:37:10
oshulgin@ip-172-31-171-204:~$ history
    1  echo this should stay
    2  history
```

4) Enter another command:
```sh
oshulgin@ip-172-31-171-204:~$ echo this will NOT stay
this will NOT stay
oshulgin@ip-172-31-171-204:~$ history 2
    3  echo this will NOT stay
    4  history 2
```

5) And wait before `even` kills the session:
```sh
oshulgin@ip-172-31-171-204:~$ Connection to 172.31.171.204 closed by remote host.
Connection to 172.31.171.204 closed.
Connection to odd-eu-west-1.acid.zalan.do closed.
```

6) Now request the access again and check if the last command was recorded:
```sh
oshulgin@oshulgin01:~$ piu request-access -t 5 172.31.171.204 test shell history
Requesting access to host 172.31.171.204 via odd-eu-west-1.acid.zalan.do for oshulgin..
Access to host odd-eu-west-1.acid.zalan.do/52.17.102.171 for user oshulgin was granted.
You can now access your server with the following command:
ssh -tA oshulgin@odd-eu-west-1.acid.zalan.do ssh -o StrictHostKeyChecking=no oshulgin@172.31.171.204

oshulgin@oshulgin01:~$ ssh -tA oshulgin@odd-eu-west-1.acid.zalan.do ssh -o StrictHostKeyChecking=no oshulgin@172.31.171.204
oshulgin@ip-172-31-171-204:~$ history
    1  echo this should stay
    2  history
```

It wasn't.

**Comment by femueller** [comment] 2016-01-06 15:45
I will close this, since I created a PR for even and other stuff will be clarified [here](https://github.com/zalando-stups/even/pull/20).

**Closed by femueller** 2016-01-06 15:45 UTC
